locust:
  master:
    config:
      target-host: "http://frontstage.crockerm.svc.cluster.local:9000"
      collection-instrument: "http://collection-instrument.crockerm.svc.cluster.local:8080"
      collection-exercise: "http://collection-exercise.crockerm.svc.cluster.local:8080"
      survey: "http://survey.crockerm.svc.cluster.local:8080"
      security-user-name: "admin"
      security-user-password: "secret"

  worker:
    config:
      configmapName: locust-worker
      locust-script: "/locust-tasks/tasks.py"
    replicaCount: 5
  
  image:
    tag: "0.13.2"