locust:
  loadtest:
    name: performance-test
    locust_locustfile: main.py
    locust_locustfile_configmap: locust-worker
    locust_host: http://frontstage.performance.svc.cluster.local:9000
    environment:
      case: http://case.performance.svc.cluster.local:8080
      collection_exercise: http://collection-exercise.performance.svc.cluster.local:8080
      collection_instrument: http://collection-instrument.performance.svc.cluster.local:8080
      party: http://party.performance.svc.cluster.local:8080
      sample: http://sample.performance.svc.cluster.local:8080
      sample_file_uploader: http://sample-file-uploader.performance.svc.cluster.local:8080
      survey: http://survey.performance.svc.cluster.local:8080
      security_user_name: admin
      security_user_password: secret
      test_respondent_password: password
      test_respondents: 5

  worker:
    replicas: 5
    strategy:
      type: RollingUpdate
  
  image:
    repository: locustio/locust
    tag: 1.4.1