locust:
  master:
    config:
      target-host: "http://frontstage.crockerm.svc.cluster.local:9000"

  worker:
    config:
      configmapName: locust-worker
      locust-script: "/locust-tasks/tasks.py"
    replicaCount: 5